/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.practica1compiladorer.View;

import com.mycompany.practica1compiladorer.FiniteAutomat;
import com.mycompany.practica1compiladorer.Logic.ThompsonGraph;
import com.mycompany.practica1compiladorer.Model.State;
import com.mycompany.practica1compiladorer.Model.Transititon;
import com.mycompany.practica1compiladorer.Practica1Compiladores;
import java.util.List;
import javax.swing.JOptionPane;
import org.javatuples.Pair;
import org.javatuples.Triplet;

/**
 *
 * @author Raúl Gómez, Alejandro Gallego
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainTitle = new javax.swing.JLabel();
        inputRegularExpression = new javax.swing.JTextField();
        generateAutomat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainTitle.setText("RECONOCEDOR DE EXPRESIONES REGULARES");

        inputRegularExpression.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputRegularExpressionActionPerformed(evt);
            }
        });

        generateAutomat.setText("Generar autómata");
        generateAutomat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateAutomatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputRegularExpression, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainTitle))
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(generateAutomat)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(mainTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(inputRegularExpression, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(generateAutomat)
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generateAutomatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateAutomatActionPerformed
        String regularExpression = inputRegularExpression.getText();
        if (!regularExpression.equals(""))
        {
            try {
                ThompsonGraph thompsonGraph = new ThompsonGraph(regularExpression);
                Triplet<List<String>,List<State>, List<Transititon>> afdElements = Practica1Compiladores.getAFDElements(thompsonGraph);
                Pair<String[],String[][]> matrixAFDElements = Practica1Compiladores.getAFDMatrixElements(afdElements);
                JOptionPane.showMessageDialog(null, "Autómata exitoso");
                FiniteAutomat af = new FiniteAutomat(matrixAFDElements,regularExpression);
                af.setLocationRelativeTo(null);
                af.setTitle("Autómata Finito");
                af.setVisible(true);
                this.setVisible(false);
            } catch (Exception e) {
                inputRegularExpression.setText("");
                JOptionPane.showMessageDialog(null, "Expresión '"+regularExpression+"' no es válida");
            }
        } 
        else 
        {
            JOptionPane.showMessageDialog(null, "Debe ingresar una expresión");
        }
    }//GEN-LAST:event_generateAutomatActionPerformed

    private void inputRegularExpressionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputRegularExpressionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputRegularExpressionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton generateAutomat;
    private javax.swing.JTextField inputRegularExpression;
    private javax.swing.JLabel mainTitle;
    // End of variables declaration//GEN-END:variables
}
